import { Component, OnInit } from '@angular/core';
import { TableComponent } from '../../common/table/table.component';
import { ClientService } from '../../../services/client/client.service';

@Component({
  selector: 'app-main',
  standalone: true,
  imports: [TableComponent],
  templateUrl: './main.component.html',
  styleUrl: './main.component.scss',
})
export class MainComponent implements OnInit {
  displayedColumns: string[] = [
    'الرقم',
    'الاسم',
    'التوصيف',
    'الإقامة',
    'المدخل',
    'التاريخ',
    'المعدل',
    'اليوم',
  ];
  data = ELEMENT_DATA;

  constructor(public readonly clientService: ClientService) {}

  ngOnInit(): void {
    this.clientService.getAll();
  }
}

const ELEMENT_DATA = [
  {
    الرقم: 1,
    الاسم: 'Hydrogen',
    التوصيف: '1.0079',
    الإقامة: 'H',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 2,
    الاسم: 'Helium',
    التوصيف: '4.0026',
    الإقامة: 'He',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 3,
    الاسم: 'Lithium',
    التوصيف: '6.941,',
    الإقامة: 'Li',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 4,
    الاسم: 'Beryllium',
    التوصيف: '9.0122',
    الإقامة: 'Be',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 5,
    الاسم: 'Boron',
    التوصيف: '10.811',
    الإقامة: 'B',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 1,
    الاسم: 'Hydrogen',
    التوصيف: '1.0079',
    الإقامة: 'H',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 2,
    الاسم: 'Helium',
    التوصيف: '4.0026',
    الإقامة: 'He',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 3,
    الاسم: 'Lithium',
    التوصيف: '6.941,',
    الإقامة: 'Li',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 4,
    الاسم: 'Beryllium',
    التوصيف: '9.0122',
    الإقامة: 'Be',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 5,
    الاسم: 'Boron',
    التوصيف: '10.811',
    الإقامة: 'B',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 1,
    الاسم: 'Hydrogen',
    التوصيف: '1.0079',
    الإقامة: 'H',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 2,
    الاسم: 'Helium',
    التوصيف: '4.0026',
    الإقامة: 'He',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 3,
    الاسم: 'Lithium',
    التوصيف: '6.941,',
    الإقامة: 'Li',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 4,
    الاسم: 'Beryllium',
    التوصيف: '9.0122',
    الإقامة: 'Be',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 5,
    الاسم: 'Boron',
    التوصيف: '10.811',
    الإقامة: 'B',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 1,
    الاسم: 'Hydrogen',
    التوصيف: '1.0079',
    الإقامة: 'H',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 2,
    الاسم: 'Helium',
    التوصيف: '4.0026',
    الإقامة: 'He',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 3,
    الاسم: 'Lithium',
    التوصيف: '6.941,',
    الإقامة: 'Li',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 4,
    الاسم: 'Beryllium',
    التوصيف: '9.0122',
    الإقامة: 'Be',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 5,
    الاسم: 'Boron',
    التوصيف: '10.811',
    الإقامة: 'B',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 1,
    الاسم: 'Hydrogen',
    التوصيف: '1.0079',
    الإقامة: 'H',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 2,
    الاسم: 'Helium',
    التوصيف: '4.0026',
    الإقامة: 'He',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 3,
    الاسم: 'Lithium',
    التوصيف: '6.941,',
    الإقامة: 'Li',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 4,
    الاسم: 'Beryllium',
    التوصيف: '9.0122',
    الإقامة: 'Be',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
  {
    الرقم: 5,
    الاسم: 'Boron',
    التوصيف: '10.811',
    الإقامة: 'B',
    المدخل: 'adfgh',
    التاريخ: Date.now(),
    المعدل: 'sakhdjladf',
    اليوم: Date.now(),
  },
];
